- alpine:3.8
- env: LANG=ja_JP.UTF-8
- env: PATH=$PATH:/usr/local/texlive/2018/bin/x86_64-linuxmusl


# Core
- apk: git
- dev: perl
- dev: wget
- dev: xz
- dev: ca-certificates
- dev: coreutils
- apk: fontconfig
- apk: ghostscript
- apk: imagemagick
- apk: poppler-utils
- dev: binutils
- dev: findutils
- apk: libc6-compat
- run: 'wget -q http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz'
- run: 'tar zxf install-tl-unx.tar.gz'
- copy: texlive.profile
- run: './install-tl-*/install-tl -profile texlive.profile'
- copy: jumoline.sty
- run: 'mv jumoline.sty $(kpsewhich -var-value TEXMFLOCAL)/tex/latex/local/'
- run: 'mkdir -p $(kpsewhich -var-value TEXMFLOCAL)/fonts/opentype'
- run: 'wget -q "https://github.com/adobe-fonts/source-han-sans/blob/release/OTF/Japanese/SourceHanSans-Medium.otf?raw=true" -O SourceHanSans-Medium.otf'
- run: 'wget -q "https://github.com/adobe-fonts/source-han-sans/blob/release/OTF/Japanese/SourceHanSans-Bold.otf?raw=true" -O SourceHanSans-Bold.otf'
- run: 'wget -q "https://github.com/adobe-fonts/source-han-sans/raw/master/LICENSE.txt" -O SourceHanSans-LICENSE.txt'
- run: 'wget -q "https://github.com/adobe-fonts/source-han-serif/blob/release/OTF/Japanese/SourceHanSerif-Regular.otf?raw=true" -O SourceHanSerif-Regular.otf'
- run: 'wget -q "https://github.com/adobe-fonts/source-han-serif/raw/master/LICENSE.txt" -O SourceHanSerif-LICENSE.txt'
- run: 'mv SourceHan*.otf SourceHan*.txt $(kpsewhich -var-value TEXMFLOCAL)/fonts/opentype/'
- run: 'mkdir -p $(kpsewhich -var-value TEXMFLOCAL)/fonts/map/dvipdfmx'
- copy: otf-up-source.map
- run: 'mv otf-up-source.map $(kpsewhich -var-value TEXMFLOCAL)/fonts/map/dvipdfmx/'
- run: 'ln -s $(kpsewhich ptex-ipaex.map) $(kpsewhich -var-value TEXMFLOCAL)/fonts/map/dvipdfmx/ptex-source.map'
- run: 'ln -s $(kpsewhich uptex-ipaex.map) $(kpsewhich -var-value TEXMFLOCAL)/fonts/map/dvipdfmx/uptex-source.map'
- run: 'ln -s $(kpsewhich otf-ipaex.map) $(kpsewhich -var-value TEXMFLOCAL)/fonts/map/dvipdfmx/otf-source.map'
- run: 'mktexlsr'
- run: 'kanji-config-updmap-sys source'
- run: 'sed -i "s/^\(  \/\(Courier\|Helvetica\|Times-Roman\|Symbol\) \/.*\)/%\1/" /usr/share/ghostscript/*/Resource/Init/gs_pdfwr.ps'
- run: 'mkdir -p /usr/share/fonts'
- run: 'ln -s $(kpsewhich -var-value TEXMFLOCAL)/fonts/truetype/public/ipaex/ipaexg.ttf /usr/share/fonts/ipaexg.ttf'
- run: 'fc-cache -fv'

- apk: ruby
- apk: zip
- apk: ruby-json
- run: 'gem install review -v 2.5.0 --no-rdoc --no-ri'
- apk: nodejs
- dev: nodejs-npm
- run: 'npm install -g tabooular'
- run: 'npm install -g prh'
- run: 'tlmgr update --self'
- run: 'tlmgr install seqsplit caption bigfoot xcolor framed
    multirow cases pgf ifoddpage jknapltx rsfs pxpgfmark subfig marginfix tcolorbox
    mathtools calrsfs calligra cancel mathcomp doublestroke lm anyfontsize etoolbox
    kastrup ec ucs environ trimspaces palatino helvetic mathpazo pdfpages titlesec qrcode xkeyval'
- run: 'wget -q https://github.com/zr-tex8r/BXcoloremoji/archive/v0.6.zip -O BXcoloremoji.zip'
- run: 'unzip -q BXcoloremoji.zip'
- run: 'mkdir -p $(kpsewhich -var-value TEXMFLOCAL)/tex/latex/BXcoloremoji'
- run: 'mv BXcoloremoji*/*.sty $(kpsewhich -var-value TEXMFLOCAL)/tex/latex/BXcoloremoji'
- run: 'mv BXcoloremoji*/LICENSE $(kpsewhich -var-value TEXMFLOCAL)/tex/latex/BXcoloremoji'
- run: 'mv BXcoloremoji*/emoji_images $(kpsewhich -var-value TEXMFLOCAL)/tex/latex/BXcoloremoji'
- run: 'mktexlsr'

- dev: make
- dev: g++
- run: 'wget -q https://github.com/prh/rules/archive/master.zip -O rules.zip && unzip -q rules.zip'
- run: 'mv rules-master/ rules && rm -rf rules.zip'
- copy: 'rule.yml'
- run: 'mv rule.yml rules/languages/ja/ && sed -ie "s/^\(imports:\)\s*$/\1\n  - ..\/languages\/ja\/rule.yml/" /rules/media/techbooster.yml'
- run: 'gem install diff-lcs --no-rdoc --no-ri'

- run: 'wget -q https://github.com/faelys/libsoldout/archive/trunk.zip && unzip trunk.zip'
- run: 'cd libsoldout-trunk/ && make mkd2latex mkd2html && mv libsoldout.so* /usr/lib/ && mv mkd2html mkd2latex /usr/bin/'
- run: 'strip `which mkd2html` && strip `which mkd2latex`'


# Circle CI
- apk: openssh-client

# Emoji
- run: 'gem install gemoji --no-rdoc --no-ri'

# CuteRB
- apk: 'ruby-rmagick'
- run: 'gem install cuterb -N'

# Phonto
- run: 'wget -q https://github.com/lrks/phonto/releases/download/v0.0.3/phonto -O /usr/bin/phonto'
- run: 'chmod +x /usr/bin/phonto'

## Cleaning
- dev: 'file'
- run: 'rm -rf $(kpsewhich -var-value TEXMFLOCAL)/install-tl* /install-tl* /texlive.profile
          /usr/local/texlive/20*/tlpkg/ /usr/local/texlive/20*/install-tl
          /usr/local/texlive/20*/release-texlive.txt
          /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/baekmuk/
          /usr/local/texlive/20*/texmf-dist/scripts/tlcockpit
          /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/ipaex/ipagp.ttf
          /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/ipaex/ipamp.ttf
          /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/ipaex/ipam.ttf
          /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/ipaex/ipag.ttf'
- run: 'cd /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/ipaex/ && rm -f ipaexm.ttf && ln -s ipaexg.ttf ipaexm.ttf && cd /'
- run: 'cd /usr/share/ghostscript/*/Resource/CIDFSubst/ && rm -f DroidSansFallback.ttf && ln -s /usr/share/fonts/ipaexg.ttf DroidSansFallback.ttf && cd /'
- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/afm
          /usr/local/texlive/20*/texmf-dist/fonts/misc
          /usr/local/texlive/20*/texmf-dist/fonts/opentype
          trunk.zip libsoldout-trunk/ BXcoloremoji*
          /usr/local/texlive/20*/texmf-dist/fonts/map/dvips
          /usr/local/texlive/20*/texmf-dist/fonts/pk/ljfour/public/cm
          /usr/local/texlive/20*/texmf-dist/fonts/source
          /usr/local/texlive/20*/texmf-dist/dvips/
          /usr/local/texlive/20*/texmf-dist/fonts/tfm/ptex-fonts/standard/'
- rmrf:
  - '/usr/local/texlive/20*/texmf-dist/'
  - name: '*korea*'
  - name: '*chinese*'
- rmrf:
  - '/usr/local/texlive/20*/texmf-dist/fonts/'
  - name: 'times'
  - name: 'cm-super'
  - name: 'courier'
  - name: 'ncntrsbk'
  - name: 'avantgar'
  - name: 'bookman'
  - name: 'zapfchan'
  - name: 'tex-gyre'
  - name: 'charter'
  - name: 'utopia'
- run: 'rm -rf /usr/share/gtk-doc/ /usr/lib/ruby/gems/*/cache/ /usr/share/X11 /usr/share/alsa'
- rmrf:
  - '/'
  - name: '*.log'
  - name: '*.html'
  - name: '*.md'
  - name: '*.ini'
  - name: '*.example'
  - name: '*.lua'
  - name: '*.c'
  - name: '*.h'
  - name: '*.ins'
  - name: '*.gif'
  - name: '*.jpg'
  - name: '*.ico'
  - name: '*.zip'
  - name: '*.exe'
  - name: '*.*gz'
  - name: '*README*'
  - name: '*hiramin*'
  - name: '*hirakaku*'
  - name: '*hiramaru*'
  - name: '*.svg'
  - name: 'doc'
  - name: '*sample*'
  - name: '*example*'
  - name: '*manual*'
  - name: '*beamer*'
  - name: 'demo'
  - name: 'tests'
  - name: 'debian'
  - name: 'lua*tex'
  - name: 'ptex'
  - name: 'uptex'
  - name: 'xe*tex'
  - name: 'images'
  - name: 'VLGothic'
  - name: '*.png'
  - name: '*.lock'
  - name: '*.git'
  - name: 'test.js'
  - name: 'test'
  - name: 'Makefile'
  - name: '*jlreq*'
  - name: '*.pl'
- run: "find / -name '*.pdf' -type f | grep -v BXcoloremoji | xargs rm -rf"
- rmrf:
  - '/usr/local/texlive/'
  - name: '*.ps'
  - name: '*.eps'
- run: "find / -name '*.cls' -type f | grep -v jsbook | grep -v jsarticle | xargs rm -rf"
- run: 'find /usr/ -empty -type d | xargs rm -rf'
- run: 'find / -executable -type f | xargs file | grep "not stripped" | cut -d":" -f1 | xargs strip'
- run: 'rm -rf /root/.ash_history /root/.config /root/.gem /root/.node-gyp /root/.npm /root/.wget-hsts /usr/bin/npm /usr/lib/node_modules/npm'
- run: 'cd  /usr/local/texlive/*/bin/x86_64-linuxmusl/ && rm -rf *mpost pdf*tex teckit_compile xdvi-xaw luatex53 makeindex *mendex && cd /'
- run: 'cd /usr/local/texlive/*/texmf-dist/ && rm -rf fonts/truetype/public/arphic-ttf/ fonts/map/pdftex/ scripts/ makeindex/ && cd /'
- run: 'find / -executable -type f | xargs grep "__rawmemchr" | cut -d":" -f1 | xargs rm -rf'
- run: 'find / -xtype l | grep -v "/proc/" | xargs rm -rf'
- run: 'rm -rf /usr/libexec/ /usr/x86_64-alpine-linux-musl/ /usr/local/texlive/texmf-local/fonts/source'

# Utility
- run: 'echo lrks/desk > /etc/desk-release'
- run: 'mkdir -p /usr/local/bin'
- copy: '*.rb'
- copy: 'pdfcrop.sh'
- run: 'mv build.rb pdfcrop.sh /usr/local/bin/'
- run: 'mkdir -p /extensions'
- copy: 'extensions/*.rb'
- copy: 'locale.yml'
- run: 'mv *.rb locale.yml /extensions'
