- alpine:3.7
- env: LANG=ja_JP.UTF-8
- env: PATH=$PATH:/usr/local/texlive/2017/bin/x86_64-linux


# Core
- apk: git
- apk: perl
- dev: wget
- dev: xz
- dev: ca-certificates
- dev: coreutils
- apk: fontconfig
- apk: ghostscript
- apk: imagemagick
- apk: poppler-utils
- dev: binutils
- dev: findutils
- run: 'wget -q http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz'
- run: 'tar zxf install-tl-unx.tar.gz'
- copy: texlive.profile
- apk: libc6-compat
- run: './install-tl-*/install-tl -profile texlive.profile'
- copy: jumoline.sty
- run: 'mv jumoline.sty $(kpsewhich -var-value TEXMFLOCAL)/tex/latex/local/'
- run: 'mkdir -p $(kpsewhich -var-value TEXMFLOCAL)/fonts/opentype'
- run: 'wget -q "https://github.com/adobe-fonts/source-han-sans/blob/release/OTF/Japanese/SourceHanSans-Medium.otf?raw=true" -O SourceHanSans-Medium.otf'
- run: 'wget -q "https://github.com/adobe-fonts/source-han-sans/blob/release/OTF/Japanese/SourceHanSans-Bold.otf?raw=true" -O SourceHanSans-Bold.otf'
- run: 'wget -q "https://github.com/adobe-fonts/source-han-serif/blob/release/OTF/Japanese/SourceHanSerif-Regular.otf?raw=true" -O SourceHanSerif-Regular.otf'
- run: 'mv SourceHan*.otf $(kpsewhich -var-value TEXMFLOCAL)/fonts/opentype/'
- run: 'mkdir -p $(kpsewhich -var-value TEXMFLOCAL)/fonts/map/dvipdfmx'
- copy: otf-up-source.map
- run: 'mv otf-up-source.map $(kpsewhich -var-value TEXMFLOCAL)/fonts/map/dvipdfmx/'
- run: 'ln -s $(kpsewhich ptex-ipaex.map) $(kpsewhich -var-value TEXMFLOCAL)/fonts/map/dvipdfmx/ptex-source.map'
- run: 'ln -s $(kpsewhich uptex-ipaex.map) $(kpsewhich -var-value TEXMFLOCAL)/fonts/map/dvipdfmx/uptex-source.map'
- run: 'ln -s $(kpsewhich otf-ipaex.map) $(kpsewhich -var-value TEXMFLOCAL)/fonts/map/dvipdfmx/otf-source.map'
- run: 'mktexlsr'
- run: 'kanji-config-updmap-sys source'
- run: 'sed -i "s/^\(  \/\(Courier\|Helvetica\|Times-Roman\|Symbol\) \/.*\)/%\1/" /usr/share/ghostscript/*/Resource/Init/gs_pdfwr.ps'
- run: 'mkdir -p /usr/share/fonts'
- run: 'ln -s $(kpsewhich -var-value TEXMFLOCAL)/fonts/truetype/public/ipaex/ipaexg.ttf /usr/share/fonts/ipaexg.ttf'
- run: 'fc-cache -fv'

- apk: ruby
- apk: zip
- apk: ruby-json
- run: 'gem install review -v 2.4.0 --no-rdoc --no-ri'
- apk: nodejs
- dev: nodejs-npm
- run: 'npm install -g tabooular'
- run: 'npm install -g prh'
- apk: gzip
- run: 'wget -q https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-1-amd64.deb'
- run: 'ar x pandoc-*.deb'
- run: 'tar Jxf data.tar.xz "./usr/bin/pandoc"'
- run: 'gzexe /usr/bin/pandoc'

- run: 'tlmgr install dvipng seqsplit float caption bigfoot xcolor framed wrapfig
    multirow cases pgf ifoddpage jknapltx rsfs pxpgfmark subfig marginfix tcolorbox
    mathtools listings pgfornament calrsfs calligra cancel mathcomp oubraces
    spalign systeme trfsigns witharrows mathtools tensor doublestroke'
- run: 'tlmgr install etoolbox kastrup'
- run: 'wget -q https://github.com/zr-tex8r/BXcoloremoji/archive/v0.5.zip -O BXcoloremoji.zip'
- run: 'unzip -q BXcoloremoji.zip'
- run: 'mkdir -p $(kpsewhich -var-value TEXMFLOCAL)/tex/latex/BXcoloremoji'
- run: 'mv BXcoloremoji*/*.sty $(kpsewhich -var-value TEXMFLOCAL)/tex/latex/BXcoloremoji'
- run: 'mv BXcoloremoji*/emoji_images $(kpsewhich -var-value TEXMFLOCAL)/tex/latex/BXcoloremoji'
- run: 'mktexlsr'

- dev: python
- dev: pkgconfig
- dev: cairo-dev
- dev: make
- dev: g++
- dev: libjpeg-turbo-dev
- run: 'cd /usr/lib/ && npm install canvas && cd /'
- run: 'npm install -g colibrijs'
- env: NODE_PATH=/usr/lib/node_modules
- run: git clone --depth 1 https://github.com/prh/rules.git
- run: 'gem install diff-lcs --no-rdoc --no-ri'

# Circle CI
- apk: openssh-client


## Cleaning
#- run: 'rm -rf $(kpsewhich -var-value TEXMFLOCAL)/install-tl*'
#- run: 'rm -rf /install-tl* /texlive.profile'
#- run: 'rm -rf /usr/local/texlive/20*/tlpkg/'
#- run: 'rm -rf /usr/local/texlive/20*/install-tl'
#- run: 'rm -rf /usr/local/texlive/20*/release-texlive.txt'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/baekmuk/'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/scripts/tlcockpit'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/ipaex/ipagp.ttf'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/ipaex/ipamp.ttf'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/ipaex/ipam.ttf'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/ipaex/ipag.ttf'
#- run: 'cd /usr/local/texlive/20*/texmf-dist/fonts/truetype/public/ipaex/ && rm -f ipaexm.ttf && ln -s ipaexg.ttf ipaexm.ttf && cd /'
#- run: 'cd /usr/share/ghostscript/*/Resource/CIDFSubst/ && rm -f DroidSansFallback.ttf && ln -s /usr/share/fonts/ipaexg.ttf DroidSansFallback.ttf && cd /'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/afm'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/misc'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/opentype'
#- run: 'rm -rf /redpen/bin/redpen-server* /redpen/sample-doc/ /redpen-*.tar.gz'
#- run: 'rm -rf /redpen/js/symbol.js'
#- run: 'rm -rf pandoc-*.deb data.tar.xz debian-binary control.tar.gz'
#- run: 'rm -rf BXcoloremoji*'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/map/dvips'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/pk/ljfour/public/cm'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/source'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/dvips/'
#- run: 'rm -rf /usr/local/texlive/20*/texmf-dist/fonts/tfm/ptex-fonts/standard/'
#- rmrf:
#  - '/usr/local/texlive/20*/texmf-dist/'
#  - name: '*korea*'
#  - name: '*chinese*'
#- rmrf:
#  - '/usr/local/texlive/20*/texmf-dist/fonts/'
#  - name: 'times'
#  - name: 'cm-super'
#  - name: 'courier'
#  - name: 'ncntrsbk'
#  - name: 'avantgar'
#  - name: 'bookman'
#  - name: 'zapfchan'
#  - name: 'tex-gyre'
#  - name: 'charter'
#  - name: 'utopia'
#  - name: 'euler'
#- run: 'strip /usr/bin/getconf /usr/bin/iconv /usr/bin/getent /usr/lib/libxml2.so.2.9.4'
#- run: 'rm -rf /usr/share/gtk-doc/'
#- run: 'rm -rf /usr/lib/ruby/gems/*/cache/'
#- run: 'rm -rf /usr/share/X11 /usr/share/alsa'
#- rmrf:
#  - '/'
#  - name: '*.log'
#  - name: '*.html'
#  - name: '*.md'
#  - name: '*.ini'
#  - name: '*.example'
#  - name: '*.lua'
#  - name: '*.c'
#  - name: '*.h'
#  - name: '*.ins'
#  - name: '*.gif'
#  - name: '*.jpg'
#  - name: '*.png'  # emojiで使っとるがな...
#  - name: '*.ico'
#  - name: '*.pdf'  # だぶんこれも...
#  - name: '*.zip'
#  - name: '*.exe'
#  - name: '*.*gz'
#  - name: '*COPYING*'
#  - name: '*README*'
#  - name: '*LICENSE*'
#  - name: '*.py'
#  - name: '*.pyc'
#  - name: '*hiramin*'
#  - name: '*hirakaku*'
#  - name: '*hiramaru*'
#  - name: '*.svg'
#  - name: 'doc'
#  - name: '*sample*'
#  - name: '*example*'
#  - name: '*manual*'
#  - name: '*beamer*'
#  - name: 'demo'
#  - name: 'tests'
#  - name: 'source'
#  - name: 'lua*tex'
#  - name: 'ptex'
#  - name: 'uptex'
#  - name: 'xe*tex'
#  - name: 'images'
#  - name: 'VLGothic'
#- rmrf:
#  - '/usr/local/texlive/'
#  - name: '*.ps'
#  - name: '*.eps'
#- run: find / -name "*.cls" -type f | grep -v "jsbook" | grep -v "article" | xargs rm -rf
#- run: 'find /usr/ -empty -type d | xargs rm -rf'


# DEBUG
- run: 'tlmgr install ec'
- run: 'tlmgr install ucs'
- run: 'tlmgr install environ'
- run: 'tlmgr install trimspaces'
- run: 'tlmgr install palatino'
- run: 'tlmgr install helvetic'
- run: 'tlmgr install mathpazo'
- run: 'tlmgr install pdfpages'

# Utility
- run: 'mkdir -p /usr/local/bin'
- copy: '*.rb'
- run: 'mv build.rb /usr/local/bin/'
- run: 'mkdir -p /extensions'
- copy: 'extensions/*.rb'
- copy: 'locale.yml'
- run: 'mv *.rb locale.yml /extensions'
- copy: 'colorpicker.js'
- run: 'mv colorpicker.js /usr/local/bin/'
