booktitle: "COSMIC L0 Vol.0"                     # 本のタイトル
aut: [ "SIGCOWW" ]                               # 著者リスト (EPUBで使われる)
date: "2016-08-16"                               # 発行日
history: [
  ["2016-08-16", "2016-12-29"],                  # 「第n版 第m刷」 省略可
  ["2018-06-11", "2018-10-31", "2018-11-03", "2019-06-01"]]
prt: "同人誌印刷 銀河出版"                       # 印刷所
pbl: "SIGCOWW"                                   # 発行者
oth: "https://sigcoww.org/"                      # Webサイト 省略可
edt: "sigcoww@sigcoww.org"                       # 連絡先 省略可
feedback: "https://example.com/"                 # 連絡フォーム 省略可
msg: "https://sigcoww.org/ で既刊紹介中"         # メッセージ 省略可

container_version: "kancolle"                    # desk のバージョン 省略可
layout_hash: "29c145e8f139ac90a42b623f8c52f37f"  # layout.tex.erb のMD5ハッシュ 省略可
sty_hash: "c202f8f4271d4302373d63acabe651b2"     # sigcoww.sty のMD5ハッシュ 省略可
titlelatex: '\sigcowwpage'                       # 扉ページ 省略可
download: "https://example.sigcoww.org/?key=%s"  # ダウンロードコード用文字列 省略可
tallymark: false                                 # ページ数を正の字で表現する 省略可

debug: true
language: ja
review_version: 2.0
bookname: book
stylesheet: [ "style.css" ]
epubversion: 3
htmlversion: 5
toclevel: 1
secnolevel: 2
toc: true
coverimage: epub-cover.png
titlepage: null
colophon: true
page_metric: B5
direction: "ltr"
opf_prefix: {
  ebpaj: "http://www.ebpaj.jp/",
  ibooks: "http://vocabulary.itunes.apple.com/rdf/ibooks/vocabulary-extensions-1.0/"
}
opf_meta: {"ebpaj:guide-version": "1.1.3", "ibooks:binding": "false"}
epubmaker:
  #mathml: true
  imgmath: true
  htmlext: xhtml
  #verify_target_images: true
  #force_include_images: []
  rename_for_legacy: true
  cover_linear: true
texstyle: sigcoww
texdocumentclass: ["jsbook", "uplatex,b5j,9pt,12Q,twoside,openany"]
dvioptions: "-d 5"
pdfmaker:
  hook_beforetexcompile: "./reviewhook.rb"
  image_scale2width: true
